// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TicheteConcursCiocolata;

/************************************************************/
/**
 * 
 */
public class adaugareConcurs {
	/**
	 * 
	 */
	public Administrator Mircea;
	/**
	 * 
	 */
	public Administrator Victorita;
	/**
	 * 
	 */
	public Concurs Milka;
	/**
	 * 
	 */
	public Premiu Ghiozdan;
};
