// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TicheteConcursCiocolata;

/************************************************************/
/**
 * 
 */
public class Categorie {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	public Premiu[] premii;

	/**
	 * 
	 */
	public void afisarePremiiRamase() {
	}

	/**
	 * 
	 */
	public void afisarePremiiCastigate() {
	}

	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public Premiu[] getPremii() {
		return premii;
	}

	public void setPremii(Premiu[] premii) {
		this.premii = premii;
	}

	public Categorie(String nume, Premiu[] premii) {
		super();
		this.nume = nume;
		this.premii = premii;
	}
	
};
