// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TicheteConcursCiocolata;

/************************************************************/
/**
 * 
 */
public class Concurs {
	/**
	 * 
	 */
	private String numeConcurs;
	/**
	 * 
	 */
	public Categorie[] categorii;
	/**
	 * 
	 */
	public Participant[] participanti;

	/**
	 * 
	 */
	public void generarePremii() {
	}

	/**
	 * 
	 */
	public void reminderCastigator() {
	}

	public String getNumeConcurs() {
		return numeConcurs;
	}

	public void setNumeConcurs(String numeConcurs) {
		this.numeConcurs = numeConcurs;
	}

	public Categorie[] getCategorii() {
		return categorii;
	}

	public void setCategorii(Categorie[] categorii) {
		this.categorii = categorii;
	}

	public Participant[] getParticipanti() {
		return participanti;
	}

	public void setParticipanti(Participant[] participanti) {
		this.participanti = participanti;
	}

	public Concurs(String numeConcurs, Categorie[] categorii) {
		
		this.numeConcurs = numeConcurs;
	
	}
	
	
};
