// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TicheteConcursCiocolata;

/************************************************************/
/**
 * 
 */
public class Participant {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String telefon;
	/**
	 * 
	 */
	private String[] coduriIntroduse;

	/**
	 * 
	 */
	public void adaugareCod() {
	}

	/**
	 * 
	 */

	public void afisareNumarDeCoduriIntroduse() {
	}

	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getTelefon() {
		return telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public String[] getCoduriIntroduse() {
		return coduriIntroduse;
	}

	public void setCoduriIntroduse(String[] coduriIntroduse) {
		this.coduriIntroduse = coduriIntroduse;
	}

	public Participant(String nume, String telefon) {
		super();
		this.nume = nume;
		this.telefon = telefon;
	}

};
