// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TicheteConcursCiocolata;

/************************************************************/
/**
 * 
 */
public class Premiu {

	private String nume;
	private String dataExtragere;
	private int oraExtragere;
	private String codCastigator;
	
	public void afisare() {
		System.out.println("\tNume premiu: " +  this.nume);
		System.out.println("\tData extragere: " +  this.dataExtragere);
		System.out.println("\tOra extragere: " +  this.oraExtragere);
		System.out.println("\tCod castigator: " +  this.codCastigator);
	}
	
	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getDataExtragere() {
		return dataExtragere;
	}
	
	public void setDataExtragere(String dataExtragere) {
		this.dataExtragere = dataExtragere;
	}

	public int getOraExtragere() {
		return oraExtragere;
	}

	public void setOraExtragere(int oraExtragere) {
		this.oraExtragere = oraExtragere;
	}

	public String getCodCastigator() {
		return codCastigator;
	}

	public void setCodCastigator(String codCastigator) {
		this.codCastigator = codCastigator;
	}

	/**
	 * 
	 */

	/**
	 * 
	 */
	public void extragereCodCastigator() {

	}

	/**
	 * 
	 */
	public void verificareCastigCod() {
	}
	
	public Premiu() {

		this.nume = "";
		this.dataExtragere = "";
		this.oraExtragere = -1;
		this.codCastigator = "";
	}
	
	public Premiu(String nume, String dataExtragere, int oraExtragere, String codCastigator) {
		
		this.nume = nume;
		this.dataExtragere = dataExtragere;
		this.oraExtragere = oraExtragere;
		this.codCastigator = codCastigator;
	}

};
