// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TicheteConcursCiocolata;

/************************************************************/
/**
 * 
 */
public class Premiu {

	private String nume;
	private String dataExtragere;
	private int oraExtragere;
	private String codCastigator;
	private String codCastigator2;
	
	
	

	public String getCodCastigator2() {
		return codCastigator2;
	}

	public void setCodCastigator2(String codCastigator2) {
		this.codCastigator2 = codCastigator2;
	}

	public String getCodCastigator3() {
		return codCastigator3;
	}

	public void setCodCastigator3(String codCastigator3) {
		this.codCastigator3 = codCastigator3;
	}

	private String codCastigator3;
	
	public void afisare() {
		System.out.println("\tNume premiu: " +  this.nume);
		System.out.println("\tData extragere: " +  this.dataExtragere);
		System.out.println("\tOra extragere: " +  this.oraExtragere);
		System.out.println("\tCod castigator: " +  this.codCastigator);
	}
	
	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getDataExtragere() {
		return dataExtragere;
	}
	
	public void setDataExtragere(String dataExtragere) {
		this.dataExtragere = dataExtragere;
	}

	public int getOraExtragere() {
		return oraExtragere;
	}

	public void setOraExtragere(int oraExtragere) {
		this.oraExtragere = oraExtragere;
	}

	public String getCodCastigator() {
		return codCastigator;
	}

	public void setCodCastigator(String codCastigator) {
		this.codCastigator = codCastigator;
	}

	/**
	 * 
	 */

	/**
	 * 
	 */
	public void extragereCodCastigator() {

	}

	/**
	 * 
	 */
	public void verificareCastigCod() {
	}
	
	public Premiu() {

		this.nume = "";
		this.dataExtragere = "";
		this.oraExtragere = -1;
		this.codCastigator = "";
	}
	
	public Premiu(String nume, String dataExtragere, int oraExtragere, String codCastigator) {
		
		this.nume = nume;
		this.dataExtragere = dataExtragere;
		this.oraExtragere = oraExtragere;
		this.codCastigator = codCastigator;
	}
	public boolean verificareNumePremiu() {

        if (this.nume.equals("")) {
            return false;
        };
        if (this.nume.length() > 10) {
            return false;
        };
        return true;
    }

    public boolean verificareCodPremiu() {
    	int codCastigatorInt = Integer.parseInt(this.codCastigator);
        if(codCastigatorInt > 100) {
            return false;
        };

        if(codCastigatorInt < 0) {
            return false;
        };
        return true;
    }
   

};
